version: 2
updates:
  - package-ecosystem: nuget
    directory: /KBUI_Web
    schedule:
      interval: yearly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: yearly
